spring.application.name=gradebook
spring.datasource.url=jdbc:postgresql://localhost:5432/gradebook
spring.datasource.username=postgres
spring.datasource.password=7945
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true